# Generated by Django 2.0.4 on 2018-09-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_taken',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
